// export const dashboard_stats={
//     total_eggs:3768,
//     total_species:198,
//     egg_nest:842,
//     eggs_nursery:2926,
//     incubators:354
// }

// export const total_collection={
//     in_nest:48,
//     in_nursery:99,
//     good_collection:82,
//     discarded:33
// }

// export const transfer_details =[
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"}
//     , {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},

//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"},
//     {id:1,egg_number:9273,status:COMPLETED,species:"Rainbow Lorikeet",transfer:"Site Name XYZ", t_date:"10 Apr 2024",receive:"SITE NAME XYZ",r_date:"10 Apr 2024",nursery:"NUR1234"}
// ];


// export const egg_list_received=[
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"},
//     {id:1,species:"Rainbow Lorikeet",parent:"Trichoglossus",egg_number:"0273/24",site_name:"SITE NAME XYZ",collected:"10 Apr 2024",batch_no:"2024/0001234/3A",collector:"Jordan Stevenson"}
    
// ]

// export const egg_list_incubation =[
//     {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},
//     {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},
//     {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},
//     {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},

//     {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},

//     {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},
//     {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},
//     {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},
// ,
// {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},

// {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},
// {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},
//     {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},
//     {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41},
//     {"id":1,egg_number:"0273/24",tag:"INFERTILE",species:"Rainbow Lorikeet",days:2,stage:"Infertile",condition:"Warm",current_weight:300,percent:-5,initial_weight:315,initial_size:33.41}
    
// ]




export const dashboard_rows = [
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' },
    { no: 1, eggNumber: '0273 / 24', status: 'Completed', species: 'Rainbow Lorikeet', transferredFrom: 'Site Name XYZ', date: '10 Apr 2024', receivingAt: 'Site Name XYZ', nursery: 'NUR1234', avatarUrl: 'bird.jpg' }
    

];


export const incubationData = [
    {
      no: 1,
      eggNumber: '0273 / 24',
      species: 'Rainbow Lorikeet',
      daysIncubation: 2,
      stage: 'Infertile',
      condition: 'Warm',
      currentWeight: 300,
      initialWeight: 315,
      initialSizeL: '33.41 mm',
      initialSizeW: '22.72 mm',
      eggClutch: 3,
      clutchId: '1234',
      site: 'Site Name',
      nursery: 'Nursery Name',
      enclosure: '24 D',
      collectedOn: '1 Mar 2024',
      collectedBy: 'Jordan Stevenson',
      avatarPerson: 'modi.jpg',
      designation: 'Designation'
    },
    {
      no: 2,
      eggNumber: '0273 / 24',
      species: 'Rainbow Lorikeet',
      daysIncubation: 2,
      stage: 'Infertile',
      condition: 'Warm',
      currentWeight: 300,
      initialWeight: 315,
      initialSizeL: '33.41 mm',
      initialSizeW: '22.72 mm',
      eggClutch: 3,
      clutchId: '1234',
      site: 'Site Name',
      nursery: 'Nursery Name',
      enclosure: '24 D',
      collectedOn: '1 Mar 2024',
      collectedBy: 'Jordan Stevenson',
      avatarPerson: 'modi.jpg',
      designation: 'Designation'
    },
    {
      no: 3,
      eggNumber: '0273 / 24',
      species: 'Rainbow Lorikeet',
      daysIncubation: 2,
      stage: 'Infertile',
      condition: 'Warm',
      currentWeight: 300,
      initialWeight: 315,
      initialSizeL: '33.41 mm',
      initialSizeW: '22.72 mm',
      eggClutch: 3,
      clutchId: '1234',
      site: 'Site Name',
      nursery: 'Nursery Name',
      enclosure: '24 D',
      collectedOn: '1 Mar 2024',
      collectedBy: 'Jordan Stevenson',
      avatarPerson: 'modi.jpg',
      designation: 'Designation'
    },
    {
      no: 4,
      eggNumber: '0273 / 24',
      species: 'Rainbow Lorikeet',
      daysIncubation: 2,
      stage: 'Infertile',
      condition: 'Warm',
      currentWeight: 300,
      initialWeight: 315,
      initialSizeL: '33.41 mm',
      initialSizeW: '22.72 mm',
      eggClutch: 3,
      clutchId: '1234',
      site: 'Site Name',
      nursery: 'Nursery Name',
      enclosure: '24 D',
      collectedOn: '1 Mar 2024',
      collectedBy: 'Jordan Stevenson',
      avatarPerson: 'modi.jpg',
      designation: 'Designation'
    },
    {
      no: 5,
      eggNumber: '0273 / 24',
      species: 'Rainbow Lorikeet',
      daysIncubation: 2,
      stage: 'Infertile',
      condition: 'Warm',
      currentWeight: 300,
      initialWeight: 315,
      initialSizeL: '33.41 mm',
      initialSizeW: '22.72 mm',
      eggClutch: 3,
      clutchId: '1234',
      site: 'Site Name',
      nursery: 'Nursery Name',
      enclosure: '24 D',
      collectedOn: '1 Mar 2024',
      collectedBy: 'Jordan Stevenson',
      avatarPerson: 'modi.jpg',
      designation: 'Designation'
    },
    {
      no: 6,
      eggNumber: '0273 / 24',
      species: 'Rainbow Lorikeet',
      daysIncubation: 2,
      stage: 'Infertile',
      condition: 'Warm',
      currentWeight: 300,
      initialWeight: 315,
      initialSizeL: '33.41 mm',
      initialSizeW: '22.72 mm',
      eggClutch: 3,
      clutchId: '1234',
      site: 'Site Name',
      nursery: 'Nursery Name',
      enclosure: '24 D',
      collectedOn: '1 Mar 2024',
      collectedBy: 'Jordan Stevenson',
      avatarPerson: 'modi.jpg',
      designation: 'Designation'
    },
    {
      no: 7,
      eggNumber: '0273 / 24',
      species: 'Rainbow Lorikeet',
      daysIncubation: 2,
      stage: 'Infertile',
      condition: 'Warm',
      currentWeight: 300,
      initialWeight: 315,
      initialSizeL: '33.41 mm',
      initialSizeW: '22.72 mm',
      eggClutch: 3,
      clutchId: '1234',
      site: 'Site Name',
      nursery: 'Nursery Name',
      enclosure: '24 D',
      collectedOn: '1 Mar 2024',
      collectedBy: 'Jordan Stevenson',
      avatarPerson: 'modi.jpg',
      designation: 'Designation'
    },
    {
      no: 8,
      eggNumber: '0273 / 24',
      species: 'Rainbow Lorikeet',
      daysIncubation: 2,
      stage: 'Infertile',
      condition: 'Warm',
      currentWeight: 300,
      initialWeight: 315,
      initialSizeL: '33.41 mm',
      initialSizeW: '22.72 mm',
      eggClutch: 3,
      clutchId: '1234',
      site: 'Site Name',
      nursery: 'Nursery Name',
      enclosure: '24 D',
      collectedOn: '1 Mar 2024',
      collectedBy: 'Jordan Stevenson',
      avatarPerson: 'modi.jpg',
      designation: 'Designation'
    },
    {
      no: 9,
      eggNumber: '0273 / 24',
      species: 'Rainbow Lorikeet',
      daysIncubation: 2,
      stage: 'Infertile',
      condition: 'Warm',
      currentWeight: 300,
      initialWeight: 315,
      initialSizeL: '33.41 mm',
      initialSizeW: '22.72 mm',
      eggClutch: 3,
      clutchId: '1234',
      site: 'Site Name',
      nursery: 'Nursery Name',
      enclosure: '24 D',
      collectedOn: '1 Mar 2024',
      collectedBy: 'Jordan Stevenson',
      avatarPerson: 'modi.jpg',
      designation: 'Designation'
    },
    {
      no: 10,
      eggNumber: '0273 / 24',
      species: 'Rainbow Lorikeet',
      daysIncubation: 2,
      stage: 'Infertile',
      condition: 'Warm',
      currentWeight: 300,
      initialWeight: 315,
      initialSizeL: '33.41 mm',
      initialSizeW: '22.72 mm',
      eggClutch: 3,
      clutchId: '1234',
      site: 'Site Name',
      nursery: 'Nursery Name',
      enclosure: '24 D',
      collectedOn: '1 Mar 2024',
      collectedBy: 'Jordan Stevenson',
      avatarPerson: 'modi.jpg',
      designation: 'Designation'
    }
  ];

  export const eggData = [
    {
      no: 1,
      species: 'Rainbow Lorikeet',
      eggNumber: '0273 / 24',
      siteName: 'Site Name XYZ',
      collectedOn: '10 Apr 2024',
      batchNo: '2024/0001234/3A',
      status: 'Intact',
      collectedBy: 'Jordan Stevenson',
      designation: 'Designation',
      avatarUrl: 'bird.jpg',
      avatarPerson: 'modi.jpg',
    },
    {
      no: 2,
      species: 'Rainbow Lorikeet',
      eggNumber: '0273 / 24',
      siteName: 'Site Name XYZ',
      collectedOn: '10 Apr 2024',
      batchNo: '2024/0001234/3A',
      status: 'Rotten',
      collectedBy: 'Jordan Stevenson',
      designation: 'Designation',
      avatarUrl: 'bird.jpg',
      avatarPerson: 'modi.jpg',
    },
    {
      no: 3,
      species: 'Rainbow Lorikeet',
      eggNumber: '0273 / 24',
      siteName: 'Site Name XYZ',
      collectedOn: '10 Apr 2024',
      batchNo: '2024/0001234/3A',
      status: 'Rotten',
      collectedBy: 'Jordan Stevenson',
      designation: 'Designation',
      avatarUrl: 'bird.jpg',
      avatarPerson: 'modi.jpg',
    },
    {
      no: 4,
      species: 'Rainbow Lorikeet',
      eggNumber: '0273 / 24',
      siteName: 'Site Name XYZ',
      collectedOn: '10 Apr 2024',
      batchNo: '2024/0001234/3A',
      status: 'Rotten',
      collectedBy: 'Jordan Stevenson',
      designation: 'Designation',
      avatarUrl: 'bird.jpg',
      avatarPerson: 'modi.jpg',
    },
  
    {
      no: 5,
      species: 'Rainbow Lorikeet',
      eggNumber: '0273 / 24',
      siteName: 'Site Name XYZ',
      collectedOn: '10 Apr 2024',
      batchNo: '2024/0001234/3A',
      status: 'Rotten',
      collectedBy: 'Jordan Stevenson',
      designation: 'Designation',
      avatarUrl: 'bird.jpg',
      avatarPerson: 'modi.jpg',
    },
    {
      no: 6,
      species: 'Rainbow Lorikeet',
      eggNumber: '0273 / 24',
      siteName: 'Site Name XYZ',
      collectedOn: '10 Apr 2024',
      batchNo: '2024/0001234/3A',
      status: 'Rotten',
      collectedBy: 'Jordan Stevenson',
      designation: 'Designation',
      avatarUrl: 'bird.jpg',
      avatarPerson: 'modi.jpg',
    },
    {
      no: 7,
      species: 'Rainbow Lorikeet',
      eggNumber: '0273 / 24',
      siteName: 'Site Name XYZ',
      collectedOn: '10 Apr 2024',
      batchNo: '2024/0001234/3A',
      status: 'Rotten',
      collectedBy: 'Jordan Stevenson',
      designation: 'Designation',
      avatarUrl: 'bird.jpg',
      avatarPerson: 'modi.jpg',
    },
    {
      no: 8,
      species: 'Rainbow Lorikeet',
      eggNumber: '0273 / 24',
      siteName: 'Site Name XYZ',
      collectedOn: '10 Apr 2024',
      batchNo: '2024/0001234/3A',
      status: 'Rotten',
      collectedBy: 'Jordan Stevenson',
      designation: 'Designation',
      avatarUrl: 'bird.jpg',
      avatarPerson: 'modi.jpg',
    }
  ];